ESSU_PRIMARY = "#2E8B57"
ESSU_WARNING = "#C99700"
ESSU_ERROR = "#B22222"
LOCKED_TONE = "#3E6A8E"

UI_BG = "#F5F6F8"
CARD_BG = "#FFFFFF"
TEXT_PRIMARY = "#1F1F1F"
TEXT_SECONDARY = "#6E6E6E"
BORDER_SUBTLE = "#E0E0E0"
DARK_TEXT_SECONDARY = "#D1D9EA"

STATUS_COLORS = {
    "ONLINE (HEALTHY)": ESSU_PRIMARY,
    "ONLINE (DEGRADED: VIDEO DELAY)": ESSU_WARNING,
    "ONLINE (SENSOR STALE)": ESSU_WARNING,
    "ONLINE (SENSOR DATA WAITING)": ESSU_WARNING,
    "OFFLINE (NO HEARTBEAT)": ESSU_ERROR,
    "LOCKED (MANUAL/TIMER)": LOCKED_TONE,
}

BUTTON_PRIMARY = {
    "fg_color": ESSU_PRIMARY,
    "hover_color": "#277A4C",
    "text_color": "#FFFFFF",
}

BUTTON_NEUTRAL = {
    "fg_color": "#DDE5DE",
    "hover_color": "#CFD8D0",
    "text_color": TEXT_PRIMARY,
}

BUTTON_WARNING = {
    "fg_color": "#EFE3BF",
    "hover_color": "#E6D7AA",
    "text_color": TEXT_PRIMARY,
}